CREATE TABLE customer (
    id         VARCHAR(100) PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE load_funds_attempt (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id               VARCHAR(100) NOT NULL,
    load_funds_id             VARCHAR(100) NOT NULL,
    -- Using cents to avoid using floats.
    amount_cents              BIGINT       NOT NULL,
    status                    VARCHAR(20)  NOT NULL,
    rejection_reason          VARCHAR(50),
    -- This is the time in each event we receive.
    processed_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- This is the time received event is saved to the table.
    created_at                TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_load_funds_attempt_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT uq_load_funds_attempt_customer_load UNIQUE (customer_id, load_funds_id),
    CONSTRAINT chk_amount_positive CHECK (amount_cents > 0),
    CONSTRAINT chk_status CHECK (status IN ('ACCEPTED', 'DECLINED')),
    CONSTRAINT chk_rejection_reason CHECK (
        (status = 'ACCEPTED' AND rejection_reason IS NULL) OR
        (status = 'DECLINED' AND rejection_reason IS NOT NULL)
    ),
    CONSTRAINT chk_rejection_reason_value CHECK (
        rejection_reason IS NULL OR rejection_reason IN (
            'DAILY_COUNT_EXCEEDED',
            'DAILY_AMOUNT_EXCEEDED',
            'WEEKLY_AMOUNT_EXCEEDED'
        )
    )
);

-- Helps optimize reading queries for evaluating decision
CREATE INDEX idx_load_funds_attempt_velocity
    ON load_funds_attempt (customer_id, status, processed_at);
